Python 3.13.12 (tags/v3.13.12:1cbe481, Feb  3 2026, 18:22:25) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> a=int(input("10")
...       b=int(input("5")
...             
SyntaxError: invalid syntax. Perhaps you forgot a comma?
>>> a=5
...             
>>> b=3
...             
>>> print('sum is: ", a+b)
...       
SyntaxError: unterminated string literal (detected at line 1)
>>> print("sum is : ", a+b)
...       
sum is :  8
>>> print("difference is : ", a-b)
...       
difference is :  2
>>> print("product is : ", a*b)
...       
product is :  15
>>> print("modulus is : ", a%b)
...       
modulus is :  2
>>> print("division is : ", a/b)
...       
division is :  1.6666666666666667
>>> print ("floor division is : ", a//b)
...       
floor division is :  1
>>> print("exponential division is : ", a**b)
...       
exponential division is :  125
